config/routes.rb
Presidents::Application.routes.draw do
  resources :presidents

  resources :users

  

end

app/models/president.rb
class President < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/presidents_controller.rb
class PresidentsController < ApplicationController
  before_action :set_president, only: [:show, :edit, :update, :destroy]

  # GET /presidents
  # GET /presidents.json
  def index
    @presidents = President.all
  end

  # GET /presidents/1
  # GET /presidents/1.json
  def show
  end

  # GET /presidents/new
  def new
    @president = President.new
  end

  # GET /presidents/1/edit
  def edit
  end

  # POST /presidents
  # POST /presidents.json
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_president
      @president = President.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def president_params
      params.require(:president).permit(:presidency, :president, :took_office, :left_office, :party, :picture, :state, :term, :biography)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presidents_helper.rb
module PresidentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Presidents</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/presidents/_form.html.erb
<%= form_for(@president) do |f| %>
  <% if @president.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@president.errors.count, "error") %> prohibited this president from being saved:</h2>

      <ul>
      <% @president.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :presidency %><br>
    <%= f.text_field :presidency %>
  </div>
  <div class="field">
    <%= f.label :president %><br>
    <%= f.text_field :president %>
  </div>
  <div class="field">
    <%= f.label :took_office %><br>
    <%= f.text_field :took_office %>
  </div>
  <div class="field">
    <%= f.label :left_office %><br>
    <%= f.text_field :left_office %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presidents/edit.html.erb
<h1>Editing president</h1>

<%= render 'form' %>

<%= link_to 'Show', @president %> |
<%= link_to 'Back', presidents_path %>

app/views/presidents/index.html.erb
<h1>Listing presidents</h1>

<table>
  <thead>
    <tr>
      <th>Presidency</th>
      <th>President</th>
      <th>Took office</th>
      <th>Left office</th>
      <th>Party</th>
      <th>Picture</th>
      <th>State</th>
      <th>Term</th>
      <th>Biography</th>
    </tr>
  </thead>

  <tbody>
    <% @presidents.each do |president| %>
      <tr>
        <td><%= president.presidency %></td>
        <td><%= president.president %></td>
        <td><%= president.took_office %></td>
        <td><%= president.left_office %></td>
        <td><%= president.party %></td>
        <td><%= president.picture %></td>
        <td><%= president.state %></td>
        <td><%= president.term %></td>
        <td><%= president.biography %></td>
        <td><%= link_to 'Show', president %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New President', new_president_path %>

app/views/presidents/new.html.erb
<h1>New president</h1>

<%= render 'form' %>

<%= link_to 'Back', presidents_path %>

app/views/presidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Presidency:</strong>
  <%= @president.presidency %>
</p>

<p>
  <strong>President:</strong>
  <%= @president.president %>
</p>

<p>
  <strong>Took office:</strong>
  <%= @president.took_office %>
</p>

<p>
  <strong>Left office:</strong>
  <%= @president.left_office %>
</p>

<p>
  <strong>Party:</strong>
  <%= @president.party %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @president.picture %>
</p>

<p>
  <strong>State:</strong>
  <%= @president.state %>
</p>

<p>
  <strong>Term:</strong>
  <%= @president.term %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @president.biography %>
</p>


<%= link_to 'Back', presidents_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>